# Generated by Django 5.1.3 on 2025-08-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='temporary_coins',
            field=models.IntegerField(default=0),
        ),
    ]
