# Generated by Django 5.1.3 on 2025-08-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_core_temporary_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='temporary_coins',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
    ]
