# Generated by Django 5.1.3 on 2025-08-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_alter_core_temporary_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='temporary_coins',
            field=models.IntegerField(default=0),
        ),
    ]
